services:
  nginx:
    image: nginx:latest
    container_name: aquastyle-nginx
    working_dir: /var/www/html
    depends_on:
      - php-fpm
    volumes:
      - .:/var/www/html
      - ./.docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "${NGINX_PORT}:80"

  php-fpm:
    container_name: aquastyle-php-fpm
    build:
      context: .docker/php-fpm
      args:
        UID: ${UID}
        GID: ${GID}
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db:
    container_name: aquastyle-db
    image: mysql:8.4
    volumes:
      - aquastyle-db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"

  nodejs:
    image: node:25
    container_name: aquastyle-nodejs
    working_dir: /var/www/html
    user: "${UID}:${GID}"
    volumes:
      - .:/var/www/html
    ports:
      - "127.0.0.1:5173:5173"
    command: sh -c "[ -d node_modules ] || npm ci && npm run dev"

volumes:
  aquastyle-db-data:
