services:
  nginx:
    image: nginx:latest
    container_name: aquastyle-nginx-prod
    working_dir: /var/www/html
    depends_on:
      - php-fpm
    volumes:
      - .:/var/www/html
      - ./.docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "${NGINX_PORT}:80"
    restart: unless-stopped

  php-fpm:
    container_name: aquastyle-php-fpm-prod
    build:
      context: .docker/php-fpm
      args:
        UID: ${UID}
        GID: ${GID}
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    restart: unless-stopped

  db:
    container_name: aquastyle-db-prod
    image: mysql:8.4
    volumes:
      - aquastyle-db-data-prod:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"
    restart: unless-stopped

volumes:
  aquastyle-db-data-prod:
